CREATE TABLE CERBERUS_PING_INFO (
	ID BIGINT NOT NULL PRIMARY KEY, 
	ADDRESS VARCHAR(256) NOT NULL, 
	MACHINENAME VARCHAR(256) NOT NULL, 
	RECEIVEDTIME BIGINT	
);

CREATE TABLE KVP_PROPERTIES (
	KEY_ENTRY VARCHAR(512) NOT NULL PRIMARY KEY,
	VALUE_ENTRY VARCHAR(1024) NOT NULL,
	DESCRIPTION VARCHAR(512)
);

CREATE TABLE TARGET_DIRECTORIES (
	ID BIGINT NOT NULL PRIMARY KEY,
	ABSOLUTE_PATH VARCHAR(256) NOT NULL
);

CREATE TABLE FILE_MANAGER_ENTRIES (
	ID BIGINT NOT NULL PRIMARY KEY,
	CLASSNAME VARCHAR(512)
);

CREATE TABLE FILE_MANAGERS (
	ID BIGINT NOT NULL PRIMARY KEY,
	TARGET_DIRECTORY BIGINT REFERENCES TARGET_DIRECTORIES(ID),
	FILE_MANAGER_KEY BIGINT REFERENCES FILE_MANAGER_ENTRIES(ID),
	INTERVAL VARCHAR(32) NULL,
	PATTERN VARCHAR(128) NULL,
	ENABLED INT NOT NULL,
	REQUIRES_FILES INT NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,
	PARAMETERS VARCHAR(512) NULL
);

CREATE TABLE NOTIFICATION_ACTIONS (
	ID BIGINT NOT NULL PRIMARY KEY,
	ACTION_CLASSNAME VARCHAR(64),
	REQUESTOR_CLASSNAME VARCHAR(64),
	REQUESTOR_KEY VARCHAR(64),
	ENABLED INT NOT NULL
);

COMMIT;
